# Auto-generated by 13_make_shards.py -- do not edit by hand.
# Machine 3 of 3. Predicted wall time 38.9 days.
#
# Runs strictly sequentially: two concurrent jobs peak ~7 GB RSS each and
# caused an out-of-memory crash earlier in this project.
#
# Arms for one (variant, dataset, seed) are kept on the SAME machine because
# the sparse arm warm-starts from that unit's adaptive checkpoint.
#
# Safe to re-run: every call passes --resume, so finished units skip and an
# interrupted one continues from its last completed epoch.

# Paths are relative to this script, so the folder can live anywhere.
$here = Split-Path -Parent $MyInvocation.MyCommand.Definition
Set-Location $here

# Uses "python" from PATH (activate the conda env first). Override with:
#   $env:MKUNET_PY = "C:\path\to\python.exe"
$py = if ($env:MKUNET_PY) { $env:MKUNET_PY } else { "python" }

if (-not (Get-Command $py -ErrorAction SilentlyContinue)) {
    Write-Output "ERROR: python not found. Activate the conda environment, or set $env:MKUNET_PY to the interpreter path."; exit 1
}

Write-Output "=== S/EM/seed42   [$(Get-Date -Format 'MM-dd HH:mm')] ==="
if (-not (Test-Path "data/cell/target/EM/train/images")) {
  Write-Output "  SKIP S/EM/seed42: data/cell/target/EM not prepared"
} else {
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 1 3 5 --network MK_UNet_S --dataset EM --data_root data/cell/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 3 5 --network MK_UNet_S --dataset EM --data_root data/cell/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode adaptive_soft --network MK_UNet_S --dataset EM --data_root data/cell/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  $src = Get-ChildItem "path A\runs" -Directory -Filter "EM_MK_UNet_S_adaptive_soft_k135_auxFalse_e200_seed42_t*" -ErrorAction SilentlyContinue | Sort-Object Name | Select-Object -Last 1
  if (-not $src) { Write-Output "  SKIP sparse: no adaptive run" }
  else {
    $ck = Join-Path $src.FullName "best.pth"
    & $py -W ignore "path A\05_train.py" --routing_mode sparse_top1 --lr 0.0003 --network MK_UNet_S --dataset EM --data_root data/cell/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 120 --anneal_epochs 40 --init_from "$ck"
  }
}

Write-Output "=== T/BUSI/seed42   [$(Get-Date -Format 'MM-dd HH:mm')] ==="
if (-not (Test-Path "data/busi/target/BUSI/train/images")) {
  Write-Output "  SKIP T/BUSI/seed42: data/busi/target/BUSI not prepared"
} else {
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 1 3 5 --network MK_UNet_T --dataset BUSI --data_root data/busi/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 3 5 --network MK_UNet_T --dataset BUSI --data_root data/busi/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode adaptive_soft --network MK_UNet_T --dataset BUSI --data_root data/busi/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  $src = Get-ChildItem "path A\runs" -Directory -Filter "BUSI_MK_UNet_T_adaptive_soft_k135_auxFalse_e200_seed42_t*" -ErrorAction SilentlyContinue | Sort-Object Name | Select-Object -Last 1
  if (-not $src) { Write-Output "  SKIP sparse: no adaptive run" }
  else {
    $ck = Join-Path $src.FullName "best.pth"
    & $py -W ignore "path A\05_train.py" --routing_mode sparse_top1 --lr 0.0003 --network MK_UNet_T --dataset BUSI --data_root data/busi/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 120 --anneal_epochs 40 --init_from "$ck"
  }
}

Write-Output "=== T/ClinicDB/seed42   [$(Get-Date -Format 'MM-dd HH:mm')] ==="
if (-not (Test-Path "data/polyp/target/ClinicDB/train/images")) {
  Write-Output "  SKIP T/ClinicDB/seed42: data/polyp/target/ClinicDB not prepared"
} else {
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 1 3 5 --network MK_UNet_T --dataset ClinicDB --data_root data/polyp/target --img_size 352 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 3 5 --network MK_UNet_T --dataset ClinicDB --data_root data/polyp/target --img_size 352 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode adaptive_soft --network MK_UNet_T --dataset ClinicDB --data_root data/polyp/target --img_size 352 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  $src = Get-ChildItem "path A\runs" -Directory -Filter "ClinicDB_MK_UNet_T_adaptive_soft_k135_auxFalse_e200_seed42_t*" -ErrorAction SilentlyContinue | Sort-Object Name | Select-Object -Last 1
  if (-not $src) { Write-Output "  SKIP sparse: no adaptive run" }
  else {
    $ck = Join-Path $src.FullName "best.pth"
    & $py -W ignore "path A\05_train.py" --routing_mode sparse_top1 --lr 0.0003 --network MK_UNet_T --dataset ClinicDB --data_root data/polyp/target --img_size 352 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 120 --anneal_epochs 40 --init_from "$ck"
  }
}

Write-Output "=== S/BUSI/seed42   [$(Get-Date -Format 'MM-dd HH:mm')] ==="
if (-not (Test-Path "data/busi/target/BUSI/train/images")) {
  Write-Output "  SKIP S/BUSI/seed42: data/busi/target/BUSI not prepared"
} else {
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 1 3 5 --network MK_UNet_S --dataset BUSI --data_root data/busi/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 3 5 --network MK_UNet_S --dataset BUSI --data_root data/busi/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode adaptive_soft --network MK_UNet_S --dataset BUSI --data_root data/busi/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  $src = Get-ChildItem "path A\runs" -Directory -Filter "BUSI_MK_UNet_S_adaptive_soft_k135_auxFalse_e200_seed42_t*" -ErrorAction SilentlyContinue | Sort-Object Name | Select-Object -Last 1
  if (-not $src) { Write-Output "  SKIP sparse: no adaptive run" }
  else {
    $ck = Join-Path $src.FullName "best.pth"
    & $py -W ignore "path A\05_train.py" --routing_mode sparse_top1 --lr 0.0003 --network MK_UNet_S --dataset BUSI --data_root data/busi/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 120 --anneal_epochs 40 --init_from "$ck"
  }
}

Write-Output "=== S/ClinicDB/seed42   [$(Get-Date -Format 'MM-dd HH:mm')] ==="
if (-not (Test-Path "data/polyp/target/ClinicDB/train/images")) {
  Write-Output "  SKIP S/ClinicDB/seed42: data/polyp/target/ClinicDB not prepared"
} else {
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 1 3 5 --network MK_UNet_S --dataset ClinicDB --data_root data/polyp/target --img_size 352 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 3 5 --network MK_UNet_S --dataset ClinicDB --data_root data/polyp/target --img_size 352 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode adaptive_soft --network MK_UNet_S --dataset ClinicDB --data_root data/polyp/target --img_size 352 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  $src = Get-ChildItem "path A\runs" -Directory -Filter "ClinicDB_MK_UNet_S_adaptive_soft_k135_auxFalse_e200_seed42_t*" -ErrorAction SilentlyContinue | Sort-Object Name | Select-Object -Last 1
  if (-not $src) { Write-Output "  SKIP sparse: no adaptive run" }
  else {
    $ck = Join-Path $src.FullName "best.pth"
    & $py -W ignore "path A\05_train.py" --routing_mode sparse_top1 --lr 0.0003 --network MK_UNet_S --dataset ClinicDB --data_root data/polyp/target --img_size 352 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 120 --anneal_epochs 40 --init_from "$ck"
  }
}

Write-Output "=== base/DSB18/seed42   [$(Get-Date -Format 'MM-dd HH:mm')] ==="
if (-not (Test-Path "data/cell/target/DSB18/train/images")) {
  Write-Output "  SKIP base/DSB18/seed42: data/cell/target/DSB18 not prepared"
} else {
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 1 3 5 --network MK_UNet --dataset DSB18 --data_root data/cell/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 3 5 --network MK_UNet --dataset DSB18 --data_root data/cell/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode adaptive_soft --network MK_UNet --dataset DSB18 --data_root data/cell/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  $src = Get-ChildItem "path A\runs" -Directory -Filter "DSB18_MK_UNet_adaptive_soft_k135_auxFalse_e200_seed42_t*" -ErrorAction SilentlyContinue | Sort-Object Name | Select-Object -Last 1
  if (-not $src) { Write-Output "  SKIP sparse: no adaptive run" }
  else {
    $ck = Join-Path $src.FullName "best.pth"
    & $py -W ignore "path A\05_train.py" --routing_mode sparse_top1 --lr 0.0003 --network MK_UNet --dataset DSB18 --data_root data/cell/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 120 --anneal_epochs 40 --init_from "$ck"
  }
}

Write-Output "=== base/ClinicDB/seed42   [$(Get-Date -Format 'MM-dd HH:mm')] ==="
if (-not (Test-Path "data/polyp/target/ClinicDB/train/images")) {
  Write-Output "  SKIP base/ClinicDB/seed42: data/polyp/target/ClinicDB not prepared"
} else {
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 1 3 5 --network MK_UNet --dataset ClinicDB --data_root data/polyp/target --img_size 352 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 3 5 --network MK_UNet --dataset ClinicDB --data_root data/polyp/target --img_size 352 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode adaptive_soft --network MK_UNet --dataset ClinicDB --data_root data/polyp/target --img_size 352 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  $src = Get-ChildItem "path A\runs" -Directory -Filter "ClinicDB_MK_UNet_adaptive_soft_k135_auxFalse_e200_seed42_t*" -ErrorAction SilentlyContinue | Sort-Object Name | Select-Object -Last 1
  if (-not $src) { Write-Output "  SKIP sparse: no adaptive run" }
  else {
    $ck = Join-Path $src.FullName "best.pth"
    & $py -W ignore "path A\05_train.py" --routing_mode sparse_top1 --lr 0.0003 --network MK_UNet --dataset ClinicDB --data_root data/polyp/target --img_size 352 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 120 --anneal_epochs 40 --init_from "$ck"
  }
}

Write-Output "=== T/ISIC18/seed42   [$(Get-Date -Format 'MM-dd HH:mm')] ==="
if (-not (Test-Path "data/isic/target/ISIC18/train/images")) {
  Write-Output "  SKIP T/ISIC18/seed42: data/isic/target/ISIC18 not prepared"
} else {
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 1 3 5 --network MK_UNet_T --dataset ISIC18 --data_root data/isic/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode fixed --kernel_sizes 3 5 --network MK_UNet_T --dataset ISIC18 --data_root data/isic/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  & $py -W ignore "path A\05_train.py" --routing_mode adaptive_soft --network MK_UNet_T --dataset ISIC18 --data_root data/isic/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 200 --lr 0.0005
  $src = Get-ChildItem "path A\runs" -Directory -Filter "ISIC18_MK_UNet_T_adaptive_soft_k135_auxFalse_e200_seed42_t*" -ErrorAction SilentlyContinue | Sort-Object Name | Select-Object -Last 1
  if (-not $src) { Write-Output "  SKIP sparse: no adaptive run" }
  else {
    $ck = Join-Path $src.FullName "best.pth"
    & $py -W ignore "path A\05_train.py" --routing_mode sparse_top1 --lr 0.0003 --network MK_UNet_T --dataset ISIC18 --data_root data/isic/target --img_size 256 --seed 42 --runs 1 --device cpu --aux_supervision False --resume --epoch 120 --anneal_epochs 40 --init_from "$ck"
  }
}

Write-Output "Machine 3 complete."